[package]
name = "neutronapi"
version = "0.1.0"
edition = "2021"
description = "Interface for apps and neutron"

[dependencies]

[features]
# used by both kernel and apps/std
types = []
# used by userspace only
interface = []
